### ISSUE TITLE
Handle non success responses (401, 403, 400, ...)

### ISSUE THREAD

**Issue by taronarm** [junyiz/zenio#1]
It's not possible to get original message and **status code** which comes from requested server.
E.g. we can not handle unauthorized (401) requests normally. For all codes except 200/2xx and 300/30x, it throws an error from which isn't possible to get original response code (approach to use regexp, which isn't nice way). **Lines 90-93**:
```
 if (code < 200 || code > 299) {
    reject(new Error('statusCode=' + code + '\n' + result))
    return
 }
```

P.S. I'll create a pull request to fix this issue. Please review and merge ))

**Comment by junyiz** [comment]
OK, thank you!
